### ISSUE TITLE
fontcolor not working in GR

### ISSUE THREAD

**Issue by blegat** [JuliaPlots/Plots.jl#1853]
```julia
using Plots
gr()
plot(xlim=(0.0, 2.0), ylim=(0.0, 2.0))
annotate!(1.0,  1.0, Plots.text("1", color))
```
is white if `color` is `:white` or `:red` and black if `color` is `:black`, `:green` or `:blue`. It works fine with Plotly or PyPlot though.

**Comment by blegat** [comment]
Adding `@show color` at
https://github.com/JuliaPlots/Plots.jl/blob/c26689fcb1d3f1054c739dbf8878ce717521667a/src/backends/gr.jl#L341
gives
```
color = RGBA{Float64}(0.0,0.0,0.0,1.0)
```

**Comment by dgleich** [comment]
Just bumped into this issue today too.

**Comment by daschw** [comment]
This issue affects all texts in Plots with GR. `plot(rand(10), xguide = "I should be red", xguidefontcolor = :red)` does not work either.
![gr_fontcolor](https://user-images.githubusercontent.com/16589944/59556450-ff3b1400-8fc2-11e9-8b2d-585e4be1d051.png)
Plots passes all the colors correctly. There seems to be a problem with `GR.settextcolorind`.
@jheinen Would you know anything about that?

**Comment by jheinen** [comment]
Works fine in `gksqt` or for PDF - seems to be related to the Cairo PNG part in GR. Will check this next week ...

**Comment by jheinen** [comment]
This problem is fixed in GR master.

**Comment by daschw** [comment]
> This problem is fixed in GR master.

It works for me in the GKS QT Term but not in Atom/Juno.

**Comment by Semptum** [comment]
The problem persists for SVGs and PNGs for GR 0.49.0 though a bit differently so I'm not sure whether I should make a separate issue but it seems like that might just be a continuation of this one.
I can set fontcolors using some colors such as :white or :red. But if I try to use some custom color it just outputs with the color #3d3d3d. It works fine for PDFs.
Here is a MNWE:


```julia
using Plots
gr()
magenta = colorant"#d33682"
Plots.plot(titlefont=font(12,"times",magenta),title="Should be magenta")
Plots.plot!(rand(10))
```

And here is the result. 
![magenta](https://user-images.githubusercontent.com/12534224/82718254-b2b38a80-9ca1-11ea-87e5-be3d277bd44b.png)
[magenta.pdf](https://github.com/JuliaPlots/Plots.jl/files/4670912/magenta.pdf)
