### ISSUE TITLE
PlotlyJS backend to Plots not working in Jupyter notebook

### ISSUE THREAD

**Issue by AtheistApe** [JuliaPlots/Plots.jl#2003]
I'm trying to get plotly to work as a backend to Plots.jl but have no luck with either Julia 0.7, Julia 1.01 or Julia 1.10.

With Julia 0.7, I get no error messages but no plots display (blank canvas).

With both Julia 1.01 and 1.10, I get the following error message:
"only png or svg allowed. got: :html"

I'm using this in a Jupyter notebook (Anaconda install) in google chrome browser.

**Comment by diegozea** [comment]
I've found the same problem using Windows 10, Julia 1.1.0, Plots 0.24.0, PlotlyJS 0.12.3 and IJulia 1.18.1 (Jupyter 5.7.0)

![image](https://user-images.githubusercontent.com/2822757/57487297-80123c00-72b0-11e9-9c28-1b384cba386f.png)

Code example:

```julia
using Plots
plotlyjs()
showlibrary(:Plots)
```

**Comment by diegozea** [comment]
Also WebIO v0.8.1, this is related to https://github.com/sglyon/PlotlyJS.jl/issues/278

**Comment by rappdw** [comment]
See #1985. Rolling Plots back to version 0.23.1 works. (I'm using JupyterLab and Julia 1.1)

**Comment by daschw** [comment]
With #2125 this should now work for Plotly, not yet for PlotlyJS though.

**Comment by ljschumacher** [comment]
Thanks, when will this be updated in a release? I'm running Plots 0.25.3 and still getting this error. (I don't know on what schedule the fixes on github enter the release versions)

**Comment by daschw** [comment]
It's included in Plots 0.26.1, which will be released soon (as soon as https://github.com/JuliaRegistries/General/pull/2547 gets merged).

**Comment by daschw** [comment]
Fixed in #2131

**Comment by arisliang** [comment]
Still not working, not sure what version I'm at, hopefully latest version, as it's just installed.

**Comment by aquohn** [comment]
Not working for me with:

IJulia v1.23.2
PlotlyJS v0.14.1
Plots v1.15.2

![image](https://user-images.githubusercontent.com/42529939/119797783-1ef84800-bf0d-11eb-8d8a-c3e34515faef.png)

In the attached image, the output cell is blank.
