### ISSUE TITLE
plotting numbers on small scale: no y-axis ticks and warning No strict ticks found

### ISSUE THREAD

**Issue by floswald** [JuliaPlots/Plots.jl#2309]
hi there

I found this:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Plots

julia> y = vcat( 0.26884394967432595,
        0.26882576785614415,
        0.26880758603796234,
        0.2687894042197805 ,
        0.2687712224015987 ,
        0.26875304058341687,
        0.26873485876523506,
        0.26871667694705326,
        0.2686984951288714 ,
        0.2686803133106896 )
10-element Array{Float64,1}:
 0.26884394967432595
 0.26882576785614415
 0.26880758603796234
 0.2687894042197805 
 0.2687712224015987 
 0.26875304058341687
 0.26873485876523506
 0.26871667694705326
 0.2686984951288714 
 0.2686803133106896 

julia> plot(y)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
```

![test](https://user-images.githubusercontent.com/1021558/70276501-c7ae6700-17b0-11ea-83fb-b1d63a114776.png)

it seems as if there is a minimum required delta between vector entries or the ticks fail. 

```
julia> y2
2-element Array{Float64,1}:
 0.26884394967432595
 0.2686803133106896 

julia> scatter(y2)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/EybJR/src/ticks.jl:168
```

![scy2](https://user-images.githubusercontent.com/1021558/70311765-923a6580-1812-11ea-9890-efb33af9860d.png)

```
julia> y3
2-element Array{Float64,1}:
 0.27   
 0.26868

julia> scatter(y3)
```
![scy3](https://user-images.githubusercontent.com/1021558/70311770-96ff1980-1812-11ea-9ac0-169174a83e25.png)

```
julia> y4
2-element Array{Float64,1}:
 0.269  
 0.26868

julia> scatter(y4)
```
![scy4](https://user-images.githubusercontent.com/1021558/70311778-9b2b3700-1812-11ea-888c-575489a7303c.png)

**Comment by daschw** [comment]
Thanks for reporting! This is probably fixed in https://github.com/JuliaPlots/PlotUtils.jl/pull/77.

**Comment by floswald** [comment]
indeed! thanks!

**Comment by Vilin97** [comment]
I am still seeing this error
```
julia> x
10-element Vector{Float64}:
 -4.2500725161431774e-17
 -7.37257477290143e-18
 -4.0766001685454967e-17
 -2.0816681711721685e-17
  0.0
  5.724587470723463e-17
  1.8214596497756474e-17
 -2.949029909160572e-17
  1.3877787807814457e-17
  3.642919299551295e-17

julia> plot(x)
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\Vasily\.julia\packages\PlotUtils\jEGKP\src\ticks.jl:191
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\Vasily\.julia\packages\PlotUtils\jEGKP\src\ticks.jl:191
```
![image](https://github.com/JuliaPlots/Plots.jl/assets/17322558/74c65002-0962-4aba-809a-f6f71a3772e2)

**Comment by Vilin97** [comment]
Interestingly, if the values are exactly equal, the ticks are fine. But when there is a small (<1e-15) separation, ticks fail.

```
julia> plot(rand(10) .* 1e-15)
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\Vasily\.julia\packages\PlotUtils\jEGKP\src\ticks.jl:191
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\Vasily\.julia\packages\PlotUtils\jEGKP\src\ticks.jl:191

julia> plot(ones(10) .* 1e-15)
```
