### ISSUE TITLE
plotlyjs backend not working again under Plots v0.29.7 on Juno v0.8.1 + Atom v1.45.0

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#2462]
@pfitzseb, @daschw, @BeastyBlacksmith ; plotlyjs backend in Plots.jl was working well earlier last week, but after updating packages to:
```
(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.12.9
  [e5e0dc1b] Juno v0.8.1
  [47be7bcc] ORCA v0.3.1
  [f0f68f2c] PlotlyJS v0.13.1
  [91a5bcdd] Plots v0.29.7
```
it just displays the black/blank plot pane in Atom/Juno.
I also updated the Atom editor itself to v1.45.0 and both julia-atom-client and ink to v0.12.3.
If I run julia from a terminal, plotlyjs backend of Plots still works. Also, if I use PlotlyJS directly, it still plot in the Juno's plot pane. So, this must be a problem specifically in the plotlyjs backend in Plots.jl. Thanks!

**Comment by BoundaryValueProblems** [comment]
I just tested the previous versions of Plots.jl, i.e., v0.29.5 and v0.29.6. Previously, at least plotlyjs backend was working under v0.29.5, but not anymore. So, I'm wondering where the problem is. Would the new Atom editor v1.45.0 be a culprit?

**Comment by daschw** [comment]
I don't think we've changed anything to the plotlyjs backend since then. Does the plotly backend work for you in atom?

**Comment by BoundaryValueProblems** [comment]
No, plotly backend is not working either under the latest setup.
So, I'll try to downgrade Atom.jl and Juno.jl, and see what happens. I'll report back.

**Comment by BoundaryValueProblems** [comment]
@daschw , I downgraded Atom.jl from v0.12.9 to v0.12.8, and tested. It didn't work.
Then, I also downgraded Juno.jl from v0.8.1 to v0.8.0, and still didn't work.
Hence, the problem may be the Atom editor v1.45.0 itself. I'm not sure how I can downgrade Atom editor to v1.44.0, so I may need to wait for a while. Very frustrating!

**Comment by BoundaryValueProblems** [comment]
It's still not clear if this is a problem of Atom editor v1.45.0. If I use PlotlyJS.jl directly for plotting, it works. But not with plotlyjs backend of Plots.jl...

**Comment by BoundaryValueProblems** [comment]
It's very interesting. After issuing a plotting command under plotlyjs backends, just in case, I ran `gui()`. Then, it worked. plotly backend also works after issuing `gui()`. But I have to issue `gui()` each time when I execute a plotting command. So, perhaps, someone could modify this behavior.
```
plotlyjs(size=(900, 600))
Plots.PlotlyJSBackend()

julia> surface(randn(100,100),c=:viridis)

julia> gui()
data: [
  "surface with fields colorbar, colorscale, hoverinfo, name, opacity, showlegend, showscale, type, x, xaxis, y, yaxis, z, zmax, and zmin"
]

layout: "layout with fields annotations, height, legend, margin, paper_bgcolor, plot_bgcolor, scene, showlegend, and width"
```

**Comment by BoundaryValueProblems** [comment]
@daschw and @pfitzseb ; do you have any idea why we need `gui()` under plotly/plotlyjs backends at this point as I pointed out above?

**Comment by daschw** [comment]
For me both plotly and plotlyjs work. I'm on Atom v1.44.0 though. No idea, why `gui()` is required in your case.

**Comment by BoundaryValueProblems** [comment]
Since the situation is the same for me on both Mac and Windows, the only difference from you seems to me the Atom editor version; I'm using v1.45.0... BTW, for the other backends, e.g., gr and pyplot, I don't need to use `gui()`.

**Comment by BoundaryValueProblems** [comment]
I just wanted to give some update. I just installed Julia v1.4.0, wiping out my previous ~/.julia folder, and added a minimal number of packages necessary to use the plotlyjs/plotly backendsof Plots.jl under Juno/Atom. The result is exactly the same as before. I still need to execute `gui()` after plotting command in the case of plotly/plotlyjs backends of Plots.jl.

**Comment by pfitzseb** [comment]
I still cannot reproduce this. Do you have anything in startup.jl or juno_startup.jl?

**Comment by BoundaryValueProblems** [comment]
I don't have juno_startup.jl; I have my startup.jl, but that is quite simple as shown below.
Also, even if I do not use this startup.jl, the situation is the same for me across platforms, i.e., MacOS, Windows, and Linux. As I mentioned earlier, directly using PlotlyJS.jl package for plotting causes no problem. Thanks for your further help!
```
atreplinit() do repl
    try
        @eval using OhMyREPL
    catch err
        @warn "error while importing OhMyREPL" err
    end
end

@eval using LinearAlgebra

try
    @eval using SparseArrays
catch err
    @warn "Could not load SparseArrays."
end

try
    @eval using Statistics
catch err
    @warn "Could not load Statistics."
end
```

**Comment by BoundaryValueProblems** [comment]
@pfitzseb ; I am very puzzled. I haven't used my MacBook Pro for a while, and I decided to update all these Julia packages, Julia itself to v1.4.0, and Atom to v1.45.0. Then, both plotly and plotlyjs backends works without issuing `gui()`. On the other hand, things haven't changed on my iMac and Windows 10 machine. My students encountered exactly the same problem: on his Windows desktop computer, he needs `gui()` while on his MacBook Pro after updating to the same setup, no `gui()` is necessary.
I also tried to copy ~/.julia/environments from my MacBook to my iMac, and rebuild the whole packages, but the situation remains the same: on my iMac & Windows machines, I need to issue `gui()` while on my MacBook Pro, I don't.  It's very frustrating. If you have any suggestion for us to try, please let me know. Thanks!

**Comment by pfitzseb** [comment]
Can you paste the output of `Juno: Debug Info` here? Maybe there's something helpful in there...

**Comment by BoundaryValueProblems** [comment]
Yes, here is the `Juno: Debug Info` output on my iMac:
```
# Atom:
Version: 1.45.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.12.4
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "layouts": {
      "defaultPanes": {
        "documentation": false
      },
      "plotPane": {},
      "workspace": {}
    }
  }
}


# ink:
Version: 0.12.3
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.3
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


# versioninfo():
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6

Status `~/.julia/environments/v1.4/Project.toml`
  [28f2ccd6] ApproxFun v0.11.10 #master (https://github.com/JuliaApproximation/ApproxFun.jl.git)
  [c52e3926] Atom v0.12.10
  [69d4c476] AutocorrelationShell v0.1.0 #master (git@gitlab.com:BoundaryValueProblems/autocorrelation-shell.git)
  [e2554f3b] Clp v0.7.1
  [717857b8] DSP v0.6.3
  [057dd010] FastTransforms v0.8.2
  [8d5ece8b] GLMNet v0.5.1
  [7073ff75] IJulia v1.20.0
  [4138dd39] JLD v0.9.2
  [033835bb] JLD2 v0.1.12
  [4076af6c] JuMP v0.21.1
  [e5e0dc1b] Juno v0.8.1
  [f51caf9e] KymatioWrapper v0.1.0 #master (git@gitlab.com:Sonar-Scattering/kymatiowrapper.git)
  [093fc24a] LightGraphs v1.3.1
  [23992714] MAT v0.7.0
  [add582a8] MLJ v0.10.2
  [cc44fc10] MTSG v1.2.0 #master (git@gitlab.com:BoundaryValueProblems/MTSG.jl.git)
  [6f286f6a] MultivariateStats v0.7.0
  [47be7bcc] ORCA v0.3.1
  [5fb14364] OhMyREPL v0.5.5
  [f0f68f2c] PlotlyJS v0.13.1
  [91a5bcdd] Plots v0.29.9 #master (https://github.com/JuliaPlots/Plots.jl.git)
  [d330b81b] PyPlot v2.8.2
  [eadaac29] ScatteringTransform v0.3.0 #master (git@gitlab.com:Sonar-Scattering/ScatteringTransform-jl.git)
  [bd728e11] Shearlab v0.3.1 #master (https://github.com/dsweber2/Shearlab.jl.git)
  [8149f6b0] WAV v1.0.3
  [29a6e085] Wavelets v0.9.0
  [c8865cad] collatingTransform v0.2.0 #master (git@gitlab.com:dsweber2/collatingtransform.git)
  [10c8d62a] pdeGenerationFortranCode v0.5.0 #master (git@gitlab.com:Sonar-Scattering/pdeGenerationFortranCode.git)
  [37e2e46d] LinearAlgebra 
  [2f01184e] SparseArrays 

```

**Comment by BoundaryValueProblems** [comment]
I also checked `Juno Debug Info` on my MacBook Pro. The only difference between these two outputs (except the obvious hardware/CPU differences) is the following lines on `julia-client`:
On my iMac:
```
# julia-client:
Version: 0.12.4
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "layouts": {
      "defaultPanes": {
        "documentation": false
      },
      "plotPane": {},
      "workspace": {}
    }
  }
}
```
On my MacBook Pro:
```
# julia-client:
Version: 0.12.4
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}
```
@pfitzseb Do you think this difference could explain the behavior I encounter?

**Comment by BoundaryValueProblems** [comment]
@daschw and @pfitzseb : It's quite interesting. I just tried the current Plots.jl master: 6e3c218. Then, when I ran `plotlyjs()`, it generated the following warning related to WebIO.jl, various plotting commands worked both on iMac and on Windows, and I didn't have to issue `gui()` anymore. But of course, it would be really nice if you could take care of the following WebIO related warning. Thanks!
```
julia> plotlyjs(size=(800,500))
[ Info: Precompiling PlotlyJS [f0f68f2c-4968-5e81-91da-67840de0976a]
┌ Warning: Error requiring WebIO from Plots:
│ LoadError: UndefVarError: @dom_str not defined
│ Stacktrace:
│  [1] top-level scope
│  [2] eval at ./boot.jl:331 [inlined]
│  [3] eval at /Users/xxx/.julia/packages/Plots/6xFI1/src/Plots.jl:1 [inlined]
│  [4] (::Plots.var"#532#535")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:85
│  [5] err(::Any, ::Module, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:42
│  [6] (::Plots.var"#531#534")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:84
│  [7] withpath(::Any, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:32
│  [8] (::Plots.var"#530#533")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:83
│  [9] listenpkg(::Any, ::Base.PkgId) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:15
│  [10] top-level scope at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:81
│  [11] include(::Module, ::String) at ./Base.jl:377
│  [12] include(::String) at /Users/xxx/.julia/packages/Plots/6xFI1/src/Plots.jl:1
│  [13] top-level scope at /Users/xxx/.julia/packages/Plots/6xFI1/src/init.jl:63
│  [14] eval at ./boot.jl:331 [inlined]
│  [15] eval at /Users/xxx/.julia/packages/Plots/6xFI1/src/Plots.jl:1 [inlined]
│  [16] (::Plots.var"#321#354")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:85
│  [17] err(::Any, ::Module, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:42
│  [18] (::Plots.var"#320#353")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:84
│  [19] withpath(::Any, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:32
│  [20] (::Plots.var"#319#352")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:83
│  [21] #invokelatest#1 at ./essentials.jl:712 [inlined]
│  [22] invokelatest at ./essentials.jl:711 [inlined]
│  [23] foreach at ./abstractarray.jl:1919 [inlined]
│  [24] loadpkg(::Base.PkgId) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:22
│  [25] #invokelatest#1 at ./essentials.jl:712 [inlined]
│  [26] invokelatest at ./essentials.jl:711 [inlined]
│  [27] require(::Base.PkgId) at ./loading.jl:930
│  [28] require(::Module, ::Symbol) at ./loading.jl:922
│  [29] top-level scope at /Users/xxx/.julia/packages/Plots/6xFI1/src/backends.jl:472
│  [30] eval at ./boot.jl:331 [inlined]
│  [31] _initialize_backend(::Plots.PlotlyJSBackend) at /Users/xxx/.julia/packages/Plots/6xFI1/src/backends.jl:471
│  [32] backend at /Users/xxx/.julia/packages/Plots/6xFI1/src/backends.jl:176 [inlined]
│  [33] plotlyjs(; kw::Base.Iterators.Pairs{Symbol,Tuple{Int64,Int64},Tuple{Symbol},NamedTuple{(:size,),Tuple{Tuple{Int64,Int64}}}}) at /Users/xxx/.julia/packages/Plots/6xFI1/src/backends.jl:33
│  [34] top-level scope at none:0
│  [35] eval at ./boot.jl:331 [inlined]
│  [36] repleval(::Module, ::Expr) at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:209
│  [37] (::Atom.var"#228#230"{Module})() at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:236
│  [38] with_logstate(::Atom.var"#228#230"{Module}, ::Base.CoreLogging.LogState) at ./logging.jl:398
│  [39] with_logger at ./logging.jl:505 [inlined]
│  [40] evalrepl(::Module, ::String) at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:227
│  [41] top-level scope at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:271
│  [42] eval(::Module, ::Any) at ./boot.jl:331
│  [43] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
│  [44] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
│  [45] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358
│ in expression starting at /Users/xxx/.julia/packages/Plots/6xFI1/src/backends/plotlyjs.jl:46
└ @ Requires ~/.julia/packages/Requires/qy6zC/src/require.jl:44
Plots.PlotlyJSBackend()
```

**Comment by n8xm** [comment]
> @daschw and @pfitzseb : It's quite interesting. I just tried the current Plots.jl master: [6e3c218](https://github.com/JuliaPlots/Plots.jl/commit/6e3c218d893908e7a95d379b5e1a7e89eb0b1a3b). Then, when I ran `plotlyjs()`, it generated the following warning related to WebIO.jl, various plotting commands worked both on iMac and on Windows, and I didn't have to issue `gui()` anymore. But of course, it would be really nice if you could take care of the following WebIO related warning. Thanks!
> 
> ```
> julia> plotlyjs(size=(800,500))
> [ Info: Precompiling PlotlyJS [f0f68f2c-4968-5e81-91da-67840de0976a]
> ┌ Warning: Error requiring WebIO from Plots:
> │ LoadError: UndefVarError: @dom_str not defined
> ...
> ```
I am having the same issue with both Juno/Atom and Jupyter Notebook, when I call `plotlyjs()`. Plotting works just fine in both cases, despite this warning.

**Comment by daschw** [comment]
Fixed in https://github.com/JuliaPlots/Plots.jl/pull/2551

**Comment by BoundaryValueProblems** [comment]
Hi, @daschw ; thanks for your effort! But I still get the following warning, which is still about WebIO, but a bit different from the previous warning:
```
julia> plotlyjs()
┌ Warning: Error requiring WebIO from Plots:
│ LoadError: UndefVarError: WebIO not defined
│ Stacktrace:
│  [1] top-level scope
│  [2] eval at ./boot.jl:331 [inlined]
│  [3] eval at /Users/xxx/.julia/packages/Plots/dpofy/src/Plots.jl:1 [inlined]
│  [4] (::Plots.var"#534#537")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:85
│  [5] err(::Any, ::Module, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:42
│  [6] (::Plots.var"#533#536")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:84
│  [7] withpath(::Any, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:32
│  [8] (::Plots.var"#532#535")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:83
│  [9] listenpkg(::Any, ::Base.PkgId) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:15
│  [10] top-level scope at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:81
│  [11] include(::Module, ::String) at ./Base.jl:377
│  [12] include(::String) at /Users/xxx/.julia/packages/Plots/dpofy/src/Plots.jl:1
│  [13] top-level scope at /Users/xxx/.julia/packages/Plots/dpofy/src/init.jl:63
│  [14] eval at ./boot.jl:331 [inlined]
│  [15] eval at /Users/xxx/.julia/packages/Plots/dpofy/src/Plots.jl:1 [inlined]
│  [16] (::Plots.var"#323#356")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:85
│  [17] err(::Any, ::Module, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:42
│  [18] (::Plots.var"#322#355")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:84
│  [19] withpath(::Any, ::String) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:32
│  [20] (::Plots.var"#321#354")() at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:83
│  [21] #invokelatest#1 at ./essentials.jl:712 [inlined]
│  [22] invokelatest at ./essentials.jl:711 [inlined]
│  [23] foreach at ./abstractarray.jl:1919 [inlined]
│  [24] loadpkg(::Base.PkgId) at /Users/xxx/.julia/packages/Requires/qy6zC/src/require.jl:22
│  [25] #invokelatest#1 at ./essentials.jl:712 [inlined]
│  [26] invokelatest at ./essentials.jl:711 [inlined]
│  [27] require(::Base.PkgId) at ./loading.jl:930
│  [28] require(::Module, ::Symbol) at ./loading.jl:922
│  [29] top-level scope at /Users/xxx/.julia/packages/Plots/dpofy/src/backends.jl:472
│  [30] eval at ./boot.jl:331 [inlined]
│  [31] _initialize_backend(::Plots.PlotlyJSBackend) at /Users/xxx/.julia/packages/Plots/dpofy/src/backends.jl:471
│  [32] backend at /Users/xxx/.julia/packages/Plots/dpofy/src/backends.jl:176 [inlined]
│  [33] plotlyjs(; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/xxx/.julia/packages/Plots/dpofy/src/backends.jl:33
│  [34] plotlyjs() at /Users/xxx/.julia/packages/Plots/dpofy/src/backends.jl:33
│  [35] top-level scope at none:0
│  [36] eval at ./boot.jl:331 [inlined]
│  [37] repleval(::Module, ::Expr) at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:209
│  [38] (::Atom.var"#228#230"{Module})() at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:236
│  [39] with_logstate(::Atom.var"#228#230"{Module}, ::Base.CoreLogging.LogState) at ./logging.jl:398
│  [40] with_logger at ./logging.jl:505 [inlined]
│  [41] evalrepl(::Module, ::String) at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:227
│  [42] top-level scope at /Users/xxx/.julia/packages/Atom/wlPiw/src/repl.jl:271
│  [43] eval(::Module, ::Any) at ./boot.jl:331
│  [44] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
│  [45] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
│  [46] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358
│ in expression starting at /Users/xxx/.julia/packages/Plots/dpofy/src/backends/plotlyjs.jl:46
└ @ Requires ~/.julia/packages/Requires/qy6zC/src/require.jl:44
Plots.PlotlyJSBackend()
```

**Comment by daschw** [comment]
Oh, thanks for the info. I can reproduce, however I do not really understand. @pfitzseb do you have an idea, what the reason for `WebIO not defined` inside a `@require WebIO` block can be?

**Comment by BoundaryValueProblems** [comment]
@daschw: Thanks a lot for your work! Now, with the latest Plots.jl, I don't see that warning message anymore. The only one I got now is:
```
julia> plotlyjs()
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.
```
But it works. So, I would close this issue soon, but one more question. As I mentioned earlier, under Atom/Juno at this point, there seems no distinction between plotly and plotlyjs backends at this point. In both case, the plots are rendered in the plot pane of Atom/Juno. It used to be different, i.e., plotly backends rendered plots on a web browser's page. Is this change intentional or the side effect of integration with WebIO? Note that if I run julia from a terminal, then these two backends behave as before, i.e., plotly renders plots on a web browser while plotlyjs generates a new graphics windows where the rendering occurs. I just want to confirm this behavior difference between terminal session and Juno/Atom session. Thanks a lot!

**Comment by daschw** [comment]
The change for plotly in Juno is intended. I think it's more convenient to have it shown in the plot pane than have it open a web browser tab. Do you see any drawbacks with this behavior?

**Comment by BoundaryValueProblems** [comment]
@daschw, thanks for your reply! I thought it's OK for both plotly and plotlyjs to behave in the same way under Juno/Atom, but just in case, I asked my student who uses plotly/plotlyjs a lot. He said the following:
> In general, I think it is OK to behave the same way. The only drawback I can think of is the following scenario: if I want to draw a lot of (big) figures and each of them need several seconds for rendering, I used to use plotly() backend to generate a lot of tabs in the browser at first and rendering them at the same time so I can save some time. If it is under Atom/Juno, I can only render one figure at a time.

Hence, my suggestion is to make plotly and plotlyjs backends behave differently under Juno/Atom as before. In fact, if plotly and plotlyjs backends behave in the same manner under Juno/Atom, there's no point of using plotly backends under Juno/Atom anyways. It would be much better to have a different option as my student described above. Thanks a lot!!

**Comment by daschw** [comment]
I would recommend to your student to disable the plot pane in atom. Then all backends behave the same as in the REPL. So with the new behavior in plotly the user has the choice between Atom plot pane and web browser. Before only the latter was possible. Hence, I disagree that plotly should behave differently from plotlyjs in Atom.

**Comment by BoundaryValueProblems** [comment]
@daschw: Thanks a lot for your suggestion! We checked that by disabling the plot pane. So, I'll close this issue now!
