### ISSUE TITLE
Plots.js+plotly() is not working -  scalefunc not defined

### ISSUE THREAD

**Issue by s-valent** [JuliaPlots/Plots.jl#2563]
Just installed the update using Pkg.

When I use `plotly()`, I can't create plots.
Even the simplest `plot([1, 2], [1, 2])` returns `UndefVarError: scalefunc not defined`

More:
```
plot([1, 2], [1, 2])

Error showing value of type Plots.Plot{Plots.PlotlyBackend}:
ERROR: UndefVarError: scalefunc not defined
Stacktrace:
 [1] plotly_axis(::Plots.Plot{Plots.PlotlyBackend}, ::Plots.Axis, ::Plots.Subplot{Plots.PlotlyBackend}) at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:179
 [2] plotly_layout(::Plots.Plot{Plots.PlotlyBackend}) at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:288
 [3] plotly_layout_json at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:349 [inlined]
 [4] plotly_html_body(::Plots.Plot{Plots.PlotlyBackend}, ::Nothing) at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:835
 [5] plotly_html_body at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:830 [inlined]
 [6] html_body at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:806 [inlined]
 [7] #standalone_html#345 at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/web.jl:7 [inlined]
 [8] write_temp_html(::Plots.Plot{Plots.PlotlyBackend}) at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/web.jl:36
 [9] standalone_html_window at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/web.jl:49 [inlined]
 [10] _display at /Users/valent/.julia/packages/Plots/7U0ob/src/backends/plotly.jl:876 [inlined]
 [11] display(::Plots.PlotsDisplay, ::Plots.Plot{Plots.PlotlyBackend}) at /Users/valent/.julia/packages/Plots/7U0ob/src/output.jl:161
 [12] display(::Any) at ./multimedia.jl:323
 [13] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [14] invokelatest at ./essentials.jl:711 [inlined]
 [15] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:161
 [16] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
 [17] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
 [18] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [19] invokelatest at ./essentials.jl:711 [inlined]
 [20] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354
 [21] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
 [22] run_repl(::REPL.AbstractREPL, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
 [23] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [24] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [25] invokelatest at ./essentials.jl:711 [inlined]
 [26] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [27] exec_options(::Base.JLOptions) at ./client.jl:305
 [28] _start() at ./client.jl:484
```

**Comment by daschw** [comment]
Thanks for reporting. That's fixed in https://github.com/JuliaPlots/Plots.jl/pull/2562. Will be released soon.

**Comment by donovaly** [comment]
> Thanks for reporting. That's fixed in #2562. Will be released soon.

I updated to Plot 1.2.0 but the issue is still there:

```
import Plots
Plots.plotly()
Plots.scatter(rand(10), rand(10))
```

leads to (using Julia 1.4):

```
UndefVarError: scalefunc not defined

Stacktrace:
 [1] plotly_axis(::Plots.Plot{Plots.PlotlyBackend}, ::Plots.Axis, ::Plots.Subplot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:179
 [2] plotly_layout(::Plots.Plot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:288
 [3] plotly_layout_json at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:349 [inlined]
 [4] plotly_html_body(::Plots.Plot{Plots.PlotlyBackend}, ::Nothing) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:835
 [5] plotly_html_body at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:830 [inlined]
 [6] html_body at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:806 [inlined]
 [7] standalone_html(::Plots.Plot{Plots.PlotlyBackend}; title::String) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\web.jl:7
 [8] standalone_html(::Plots.Plot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\web.jl:7
 [9] _show at C:\Users\USti\.julia\packages\Plots\7U0ob\src\backends\plotly.jl:871 [inlined]
 [10] show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\output.jl:216
 [11] sprint(::Function, ::MIME{Symbol("text/html")}, ::Vararg{Any,N} where N; context::Nothing, sizehint::Int64) at .\strings\io.jl:105
 [12] sprint at .\strings\io.jl:101 [inlined]
 [13] _ijulia_display_dict(::Plots.Plot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\ijulia.jl:56
 [14] display_dict(::Plots.Plot{Plots.PlotlyBackend}) at C:\Users\USti\.julia\packages\Plots\7U0ob\src\init.jl:81
 [15] #invokelatest#1 at .\essentials.jl:712 [inlined]
 [16] invokelatest at .\essentials.jl:711 [inlined]
 [17] execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\USti\.julia\packages\IJulia\yLI42\src\execute_request.jl:112
 [18] #invokelatest#1 at .\essentials.jl:712 [inlined]
 [19] invokelatest at .\essentials.jl:711 [inlined]
 [20] eventloop(::ZMQ.Socket) at C:\Users\USti\.julia\packages\IJulia\yLI42\src\eventloop.jl:8
 [21] (::IJulia.var"#15#18")() at .\task.jl:358
```

**Comment by daschw** [comment]
Are you sure, you are using Plots 1.2? I cannot reproduce this.

**Comment by donovaly** [comment]
Yes, I just updated and re-run my notebook:

```
   Updating git-repo `https://github.com/plotly/Plotly.jl`
...
  [91a5bcdd] ↑ Plots v1.0.8 ⇒ v1.2.0
```

**Comment by donovaly** [comment]
OK, I had to explicitly rebuilt ORCA:

`Pkg.build("ORCA")`

Now it works.

**Comment by daschw** [comment]
Great

**Comment by donovaly** [comment]
> Great

Not completely because every time I restart the kernel I have to rebuild ORCA again. I opened therefore now issue #2661
