### ISSUE TITLE
Bad ticklabels and unicode error for large values with GR

### ISSUE THREAD

**Issue by AndiMD** [JuliaPlots/Plots.jl#2574]
This plotting command
```
using Plots
gr()
plot(1:1000, x->x^6)
```
spams the REPL with messages
```GKS: character ignored due to unicode error```

and produces bad ticklabels like this:
![image](https://user-images.githubusercontent.com/24719218/79136103-be618680-7db0-11ea-8c4b-f0439b2137bb.png)

My setup:
```
Plots v1.0.9
Julia Version 1.4.0
OS: Linux (x86_64-pc-linux-gnu)
```

Thanks!

**Comment by AndiMD** [comment]
Possibly related, most GR typesetting is broken. Until recently, the following produced a greek alpha. Now, the label does not show up anymore:
plot(1:10,xlabel="\\alpha")

This happened very recently, probably 1.0.8 or 1.0.9.

**Comment by daschw** [comment]
cc: @jheinen

**Comment by jheinen** [comment]
We should probably make UTF-8 the default. This works:
```julia
ENV["GKS_ENCODING"]="utf8"
using Plots
plot(1:1000, x->x^6)
```

**Comment by jheinen** [comment]
<img width="712" alt="Screen Shot 2020-04-15 at 14 51 22" src="https://user-images.githubusercontent.com/5718244/79339073-94cb6b00-7f28-11ea-8348-457a9dd12907.png">

**Comment by daschw** [comment]
> We should probably make UTF-8 the default. 

In Plots or in GR?

**Comment by jheinen** [comment]
As a short-time solution, I'd define `ENV["GKS_ENCODING"]="utf8"` before the first GR function is called, e.g. in Plots' `_display` and `_show` methods.

**Comment by jheinen** [comment]
d00920ca0eff8b7c0826246ba16eeb8620195bfd should fix it.

**Comment by AndiMD** [comment]
Thanks! Plots#master fixes the ticklabels.
However, the label formatting
```plot(1:10,xlabel="\\alpha")```
is not fixed by that.

**Comment by jheinen** [comment]
I'll check that - in the meantime (and as a workaround), you can use` L"\alpha"` (via `LaTeXStrings`) which works fine.

**Comment by AndiMD** [comment]
Thanks again. I will simply use 1.0.8 in the meantime, since LaTeXStrings have always looked too pixelated for me
![image](https://user-images.githubusercontent.com/24719218/79375137-6ebdbf00-7f58-11ea-983b-083685a7b4e2.png)

**Comment by jheinen** [comment]
Ok, so there are still some other problems. I'll check this tomorrow. Plots should use GR's new rendering engine, which - in this case - it does not.

**Comment by AndiMD** [comment]
Using 1.0.10, the LaTeXStrings actually look decent! Above image is from 1.0.8.

**Comment by AndiMD** [comment]
I realized that the utf-8 symbols now work `plot(1:10,xlabel="α")` (instead of `"\\alpha"`).
With that, I think the issue is resolved.

**Comment by eike-fokken** [comment]
For future reference:
If you have Plots precompiled via PackageCompiler and none of this seems to work for you, the following might help (it helped me):
Prepend your call

`julia --sysimage /path/to/sysimage_custom.so`

with exporting GKS_ENCODING like so:

`export GKS_ENCODING="utf-8" && julia --sysimage /path/to/sysimage_custom.so`

I didn't test whether you also need (or don't need) to call these before compiling Plots (whatever I did, in the end it worked) but I think the call to export above is enough.
