### ISSUE TITLE
Variable marker size in PyPlot

### ISSUE THREAD

**Issue by rodinalex** [JuliaPlots/Plots.jl#2652]
The Example from the Docs website:
```
pyplot()
y = rand(100)

scatter(
    y,
    zcolor = abs.(y .- 0.5),
    m = (:heat, 0.8, Plots.stroke(1, :green)),
    ms = 10 * abs.(y .- 0.5) .+ 4,
    lab = "grad",
)
```
does not work in PyPlot. The error is:

ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()')

Moreover, 

```
pgfplotsx()
scatter(y, ms = 10 * abs.(y .- 0.5) .+ 4, markeralpha = abs.(y .- 0.5))
```
works as expected, while
```
pgfplotsx()
scatter(y, ms = 10 * abs.(y .- 0.5) .+ 4)
```
makes all markers the same size.

Thank you

**Comment by daschw** [comment]
The pyplot example is fixed in https://github.com/JuliaPlots/Plots.jl/pull/2650

**Comment by BeastyBlacksmith** [comment]
I'm reopening, since the pgfplotsx issue is still to be solved

**Comment by daschw** [comment]
that's fixed with #2653, no?

**Comment by BeastyBlacksmith** [comment]
you are right, sorry for the noise ^^;

**Comment by rodinalex** [comment]
Thank you for being on top of this!
