### ISSUE TITLE
[BUG] image axis limits

### ISSUE THREAD

**Issue by andferrari** [JuliaPlots/Plots.jl#3136]
## Details

Functionality fixed in #1951 seems to be broken again. The example in #1951 gives
with `gr()`:
```
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: Length of x & y does not match the size of z.
Must be either `size(z) == (length(y), length(x))` (x & y define midpoints)
or `size(z) == (length(y)+1, length(x)+1))` (x & y define edges).
```
The output is messy with `pyplot()`and `plotly()`.

### Backends

This bug occurs on

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |    |
pyplot       |  x   |     |
plotly       |   x  |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.8.1
Backend  version (`]st -m`): GR v0.53.0
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by daschw** [comment]
This is fixed for RecipesPipeline 0.2.1 thanks to @oschulz in https://github.com/JuliaPlots/RecipesPipeline.jl/pull/71.

**Comment by andferrari** [comment]
@daschw I still have the same error with RecipesPipeline 0.2.1

**Comment by daschw** [comment]
You are right, thanks for checking! I'll look into it.
