### ISSUE TITLE
gr contour sometimes shrinks plot

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#414]
This code fails in a weird way, by shrinking the plot:

``` julia
y=[-0.997669
 -0.979084
 -0.942261
 -0.887885
 -0.81697 
 -0.730836
 -0.631088
 -0.519584
 -0.398401
 -0.269797
 -0.136167
  0.0     
  0.136167
  0.269797
  0.398401
  0.519584
  0.631088
  0.730836
  0.81697 
  0.887885
  0.942261
  0.979084
    0.997669]
gr()
contour(linspace(-0.99,0.99,23),y,rand(23,23))
```

**Comment by dlfivefifty** [comment]
<img width="597" alt="screen shot 2016-07-26 at 1 45 38 pm" src="https://cloud.githubusercontent.com/assets/1229737/17125492/3dc5a1fc-5337-11e6-9562-51b496ff0c5f.png">

**Comment by tbreloff** [comment]
I can reproduce.  Interesting to note that if you add `fill=true` then it works as expected.  The difference in the calls is this:

```julia
            if series[:fillrange] != nothing
                GR.surface(x, y, z, GR.OPTION_CELL_ARRAY)
            else
                GR.contour(x, y, h, z, 1000)
            end
```

@jheinen any idea what's going on?

**Comment by jheinen** [comment]
@tbreloff , GR.contour() never requires OpenGL, but GR.surface() probes for hardware acceleration.

**Comment by tbreloff** [comment]
@jheinen what does hardware acceleration have to do with this example?  To clarify, the problem is that the call to `GR.contour` seems to draw in a shrunken part of the screen.

**Comment by jheinen** [comment]
@tbreloff , sorry, forget the last comment. I'll try to reproduce the problem soon ...

**Comment by jheinen** [comment]
Unfortunately, this is a restriction of GR's internal contour algorithm, which only supports regular grids. In the above example, the grid is rectilinear (see ``y`` component).

You can use ``meshgrid`` and ``gridit`` to create a regular grid which can then be passed to the ``contour`` routine, but I think, this is not a good solution:

```
x, y = meshgrid(x, y)
x, y, z = gridit(vec(x), vec(y), vec(z), 50, 50)
contour(x,y,z)
``` 

The problem is on my radar and I'll try to find a better solution ... (or modify the existing algorithm)

**Comment by mkborregaard** [comment]
I can still reproduce this issue

**Comment by jheinen** [comment]
Just fixed in https://github.com/jheinen/gr/commit/fa3570affed1130ecf02e19d8e01b23dddce94be - CI build is running and new runtime will be available soon ...
![screen shot 2017-11-06 at 15 42 37](https://user-images.githubusercontent.com/5718244/32446617-c759289c-c309-11e7-90ef-29ac54863ca6.png)

**Comment by jheinen** [comment]
```julia
ENV["GRDIR"]=""; Pkg.build("GR")
import GR; GR.version()
"0.27.0.post10"
```
... should fix it

**Comment by daschw** [comment]
Great @jheinen! I'm closing this now.
@dlfivefifty Feel free to reopen if you encounter any issues.

**Comment by mkborregaard** [comment]
I still get the error - my GR version is "0.27.0" - was it somehow not completely rebuilt?

**Comment by daschw** [comment]
Oh, same here ...
How do we get to "0.27.0.post10"?

**Comment by jheinen** [comment]
Are you using GR master?

**Comment by daschw** [comment]
Yes, I think so, I will check later ...

**Comment by mkborregaard** [comment]
I'm on master, and also did a fresh `Pkg.checkout("GR")` before rebuilding.

**Comment by apalugniok** [comment]
Just checked I could reproduce the issue then I did
```
Pkg.checkout("GR")
ENV["GRDIR"]=""
Pkg.build("GR")
```
and now the issue is fixed for me.
