### ISSUE TITLE
World age issue when testing GR

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#895]
I've been trying to run our tests on 0.6 to get ready for making the transition. However, the GR tests fail because of a "world-age" issue:

```
Pkg.test("Plots")
...
 Error :: (line:272)
    Expression: image_comparison_tests(pkg, i, debug=debug, sigma=sigma, eps=eps) |> success --> true
    MethodError: no method matching emergencyclosegks()
    The applicable method may be too new: running in world age 22168, while current world is 22171.
    Closest candidates are:
      emergencyclosegks() at /Users/michael/.julia/v0.6/GR/src/GR.jl:1470 (method too new to be called from this world context.)
...
```
(the same error for every image).

**Comment by mkborregaard** [comment]
fixed by https://github.com/JuliaPlots/Plots.jl/pull/908

**Comment by mistguy** [comment]
I still have this issue using juno every time I use plot for the first time of every julia session.

**Comment by mkborregaard** [comment]
Yes, the issue is still open as #745
